export const areas = [
  {
    slug: "panglao",
    name: "Panglao Island",
    name_ko: "팡라오 섬",
    tagline: "Bohol's premier beachfront destination",
    tagline_ko: "보홀 최고의 해변 지역",
    description: `Panglao Island is the crown jewel of Bohol real estate. Connected to the mainland by two bridges, Panglao hosts some of the Philippines' finest dive sites, pristine white sand beaches, and the region's international airport — just minutes away. Foreign buyers are drawn to Panglao for its CCT condominium options, SRRV eligibility, and projected appreciation as Bohol's luxury tourism market matures.`,
    description_ko: `팡라오 섬은 보홀 부동산의 핵심입니다. 두 개의 다리로 본토와 연결된 팡라오에는 필리핀 최고의 다이빙 포인트, 순백의 해변, 그리고 지역 국제공항이 자리합니다. 외국인 구매자들은 CCT 콘도미니엄, SRRV 자격, 그리고 보홀 럭셔리 관광 시장의 성장에 따른 가치 상승 전망을 이유로 팡라오를 선택합니다.`,
    keywords: ["panglao island condos for sale", "panglao bohol property", "buy condo panglao philippines", "panglao real estate foreigners", "panglao srrv condo"],
    locationMatch: ["Panglao", "Dauis", "Totolan"],
    highlights: [
      "Minutes from Panglao International Airport",
      "World-class diving at Balicasag Island",
      "White Beach and Alona Beach — top Philippine beaches",
      "Strong tourism rental demand year-round",
      "CCT titles available — foreigners own outright",
    ],
    seoTitle: "Panglao Island Condos for Sale | Island Properties PH",
    seoDescription: "Buy a CCT condo on Panglao Island, Bohol. Beachfront developments, SRRV-eligible, full foreign ownership. Browse listings with prices from ₱2.8M.",
  },
  {
    slug: "tagbilaran",
    name: "Tagbilaran City",
    name_ko: "타그빌라란 시티",
    tagline: "Bohol's capital — the business and lifestyle hub",
    tagline_ko: "보홀의 수도 — 비즈니스와 라이프스타일의 중심",
    description: `Tagbilaran is Bohol's capital city and commercial centre — home to hospitals, universities, shopping malls, and the region's main port connecting to Cebu. For buyers who want urban convenience alongside island living, Tagbilaran offers the best of both. CCT condominiums here attract long-term residents, retirees, and investors seeking stable rental demand from the city's growing professional population.`,
    description_ko: `타그빌라란은 보홀의 수도이자 상업 중심지로 병원, 대학교, 쇼핑몰, 그리고 세부를 연결하는 주요 항구가 있습니다. 도심의 편의성과 섬 생활을 동시에 원하는 구매자에게 타그빌라란은 최적의 선택입니다. 이 지역의 CCT 콘도는 장기 거주자, 은퇴자, 그리고 도시 전문직 인구의 안정적인 임대 수요를 노리는 투자자들에게 인기입니다.`,
    keywords: ["tagbilaran condo for sale", "tagbilaran bohol property", "buy apartment tagbilaran", "tagbilaran real estate", "bohol capital city condo"],
    locationMatch: ["Tagbilaran"],
    highlights: [
      "Bohol's main hospital hub — Gov. Gallares, ACE Medical Center",
      "Direct ferry to Cebu City (2 hours)",
      "Robinsons Place Tagbilaran and Island City Mall",
      "Strong rental demand from city professionals",
      "Lower prices than Panglao with solid appreciation potential",
    ],
    seoTitle: "Tagbilaran City Condos for Sale | Island Properties PH",
    seoDescription: "Buy a CCT condo in Tagbilaran City, Bohol. Urban convenience, hospital access, ferry to Cebu. SRRV-eligible. Browse listings from ₱4.9M.",
  },
  {
    slug: "dauis",
    name: "Dauis, Panglao",
    name_ko: "다우이스, 팡라오",
    tagline: "Quiet bayside living with Panglao access",
    tagline_ko: "팡라오를 품은 조용한 베이사이드 생활",
    description: `Dauis sits on the Bohol mainland side of the Panglao bridges — quieter than beachfront Panglao but minutes from everything. The area offers some of the most competitive condo pricing in the region with easy access to Panglao beaches, the airport, and Tagbilaran city services. A favourite among buyers who want space, calm, and value without sacrificing location.`,
    description_ko: `다우이스는 팡라오 다리 건너 보홀 본토 쪽에 위치해 있어 팡라오 해변보다 조용하지만 모든 것에 가깝습니다. 팡라오 해변, 공항, 타그빌라란 도심 서비스에 쉽게 접근할 수 있으면서 지역에서 가장 경쟁력 있는 콘도 가격을 제공합니다. 입지를 포기하지 않으면서 여유, 평온, 가치를 원하는 구매자들이 선호하는 지역입니다.`,
    keywords: ["dauis bohol condo", "dauis panglao property", "buy condo dauis philippines", "dauis real estate foreigners"],
    locationMatch: ["Dauis"],
    highlights: [
      "5 minutes from Panglao International Airport",
      "10 minutes to Alona Beach",
      "Competitive pricing vs beachfront Panglao",
      "Established residential community",
      "CCT titles — full foreign ownership",
    ],
    seoTitle: "Dauis Panglao Condos for Sale | Island Properties PH",
    seoDescription: "Buy a CCT condo in Dauis, Panglao Bohol. Minutes from the airport and Alona Beach. SRRV-eligible, foreign ownership. Browse listings from ₱2.8M.",
  },
  {
    slug: "anda",
    name: "Anda, Bohol",
    name_ko: "안다, 보홀",
    tagline: "Unspoiled coastline — Bohol's best-kept secret",
    tagline_ko: "보홀의 숨겨진 보석 — 손때 묻지 않은 해안선",
    description: `Anda is Bohol's undiscovered paradise — a pristine peninsula on the island's eastern tip with powdery white beaches, crystal-clear waters, and virtually zero overdevelopment. Early buyers here are positioning ahead of what many analysts expect to be Bohol's next tourism corridor. Limited inventory, exceptional natural beauty, and a growing expat community make Anda one of the region's most compelling long-term plays.`,
    description_ko: `안다는 보홀의 발견되지 않은 파라다이스입니다. 섬의 동쪽 끝에 위치한 이 청정 반도는 순백의 해변, 투명한 바다, 그리고 거의 개발되지 않은 자연을 자랑합니다. 이 지역의 초기 구매자들은 많은 분석가들이 보홀의 차세대 관광 회랑으로 기대하는 지역에 선제적으로 투자하고 있습니다.`,
    keywords: ["anda bohol property", "anda bohol real estate", "buy land anda bohol", "anda bohol beach resort"],
    locationMatch: ["Anda"],
    highlights: [
      "Undeveloped white sand coastline",
      "No crowds — early-stage opportunity",
      "Growing expat community",
      "Long-term appreciation potential",
      "2.5 hours from Tagbilaran — scenic drive",
    ],
    seoTitle: "Anda Bohol Properties for Sale | Island Properties PH",
    seoDescription: "Buy property in Anda, Bohol. Pristine beaches, zero overdevelopment, early-stage opportunity. Browse listings from Island Properties PH.",
  },
  {
    slug: "baclayon",
    name: "Baclayon, Bohol",
    name_ko: "바클라욘, 보홀",
    tagline: "Historic charm meets expat community living",
    tagline_ko: "역사적 매력과 외국인 커뮤니티가 만나는 곳",
    description: `Baclayon is one of Bohol's oldest and most characterful municipalities — home to the famous 16th-century Baclayon Church, a UNESCO-listed heritage site, and a coastline overlooking the Bohol Sea. The area has quietly become a favourite among expats and retirees who want genuine community living away from the tourist crowds of Panglao, while staying just 10 minutes from Tagbilaran's amenities. Properties here tend to offer more space and better value than beachfront alternatives.`,
    description_ko: `바클라욘은 보홀에서 가장 오래되고 개성 있는 지역 중 하나입니다. 유네스코에 등재된 16세기 바클라욘 성당과 보홀해를 바라보는 해안선으로 유명합니다. 팡라오의 관광객 혼잡을 피해 진정한 커뮤니티 생활을 원하면서도 타그빌라란 편의시설에서 10분 거리를 유지하고 싶은 외국인 거주자와 은퇴자들이 선호하는 지역이 되었습니다.`,
    keywords: ["baclayon bohol property", "baclayon bohol real estate", "expat living baclayon bohol", "buy property baclayon philippines", "bohol heritage town real estate"],
    locationMatch: ["Baclayon"],
    highlights: [
      "10 minutes from Tagbilaran city centre",
      "UNESCO heritage town — Baclayon Church",
      "Growing expat and retiree community",
      "More space and value vs Panglao beachfront",
      "Quiet coastal living on the Bohol Sea",
    ],
    seoTitle: "Baclayon Bohol Properties for Sale | Island Properties PH",
    seoDescription: "Buy property in Baclayon, Bohol. Historic heritage town, growing expat community, 10 minutes from Tagbilaran. Browse listings at Island Properties PH.",
  },
  {
    slug: "alona-beach",
    name: "Alona Beach, Panglao",
    name_ko: "알로나 비치, 팡라오",
    tagline: "Bohol's most famous beach — and its most searched address",
    tagline_ko: "보홀에서 가장 유명한 해변",
    description: `Alona Beach is the name foreigners know first. A 1.5km stretch of white sand on Panglao Island's southern tip, Alona is surrounded by world-class dive sites, beach bars, restaurants, and a vibrant expat scene. Properties near Alona command a premium — and hold it. For buyers searching "property near Alona Beach Bohol," this is the address that needs no explanation to international buyers, rental guests, or future resale buyers.`,
    description_ko: `알로나 비치는 외국인들이 가장 먼저 알게 되는 이름입니다. 팡라오 섬 남단의 1.5km 백사장 주변에는 세계 수준의 다이빙 포인트, 비치 바, 레스토랑, 활기찬 외국인 커뮤니티가 자리합니다. 알로나 인근 매물은 프리미엄을 유지합니다. 국제 구매자, 임차인, 미래 재판매 구매자 모두에게 설명이 필요 없는 주소입니다.`,
    keywords: ["alona beach property for sale", "buy condo near alona beach", "alona beach bohol real estate", "alona beach panglao condo", "property alona beach philippines"],
    locationMatch: ["Alona", "Panglao"],
    highlights: [
      "Bohol's #1 most searched beach destination",
      "World-class diving — Balicasag Island nearby",
      "Strong short-term rental demand year-round",
      "Vibrant expat and tourist scene",
      "CCT condos available — foreigners own outright",
    ],
    seoTitle: "Alona Beach Property for Sale | Island Properties PH",
    seoDescription: "Buy property near Alona Beach, Panglao Bohol. Bohol's most famous beach address. CCT condos, SRRV-eligible, strong rental demand. Browse listings now.",
  },
  {
    slug: "loboc",
    name: "Loboc, Bohol",
    name_ko: "로복, 보홀",
    tagline: "Riverfront living in Bohol's lush interior",
    tagline_ko: "보홀 내륙의 강변 생활",
    description: `Loboc sits along the famous Loboc River — one of Bohol's most iconic natural landmarks and a top tourist destination. The town offers lush jungle surroundings, cooler inland temperatures, and a peaceful lifestyle far from beach crowds. An emerging choice for buyers seeking land or eco-resort investments, Loboc appeals to those who want nature immersion with easy access to Tagbilaran and Panglao.`,
    description_ko: `로복은 보홀의 상징적인 자연 명소이자 최고의 관광지인 로복 강변에 위치합니다. 울창한 정글 환경, 시원한 내륙 기온, 그리고 해변 혼잡에서 벗어난 평화로운 생활을 제공합니다. 자연 속 생활과 타그빌라란·팡라오 접근성을 동시에 원하는 토지 또는 에코리조트 투자자들에게 떠오르는 선택지입니다.`,
    keywords: ["loboc bohol property", "loboc river real estate", "eco resort loboc bohol", "buy land loboc bohol"],
    locationMatch: ["Loboc"],
    highlights: [
      "Along the famous Loboc River",
      "Lush jungle setting, cooler temperatures",
      "Eco-resort and land investment potential",
      "30 minutes from Tagbilaran",
      "Near Chocolate Hills — top Bohol landmark",
    ],
    seoTitle: "Loboc Bohol Properties for Sale | Island Properties PH",
    seoDescription: "Buy property along the Loboc River, Bohol. Eco-resort potential, lush jungle setting, 30 minutes from Tagbilaran. Browse listings at Island Properties PH.",
  },
  {
    slug: "alburquerque",
    name: "Alburquerque, Bohol",
    name_ko: "알부르케르케, 보홀",
    tagline: "Quiet hillside living between city and coast",
    tagline_ko: "도시와 해안 사이의 조용한 언덕 생활",
    description: `Alburquerque is a peaceful municipality tucked between Tagbilaran and the southern coast — offering hillside views, cooler air, and a genuine local community feel. It's gaining quiet interest from expats and retirees who want more space and privacy than city living offers, without being far from services. Land values remain among the most accessible in the Tagbilaran corridor.`,
    description_ko: `알부르케르케는 타그빌라란과 남부 해안 사이에 위치한 평화로운 지역으로 언덕 전망, 시원한 공기, 그리고 진정한 지역 커뮤니티 분위기를 제공합니다. 도심보다 더 넓은 공간과 프라이버시를 원하면서도 편의시설에서 멀지 않은 곳을 찾는 외국인 거주자와 은퇴자들의 조용한 관심을 받고 있습니다.`,
    keywords: ["alburquerque bohol property", "alburquerque bohol real estate", "buy land alburquerque bohol", "bohol hillside property"],
    locationMatch: ["Alburquerque"],
    highlights: [
      "15 minutes from Tagbilaran",
      "Hillside views, cooler temperatures",
      "Affordable land values",
      "Quiet, authentic local community",
      "Easy access to south coast beaches",
    ],
    seoTitle: "Alburquerque Bohol Properties for Sale | Island Properties PH",
    seoDescription: "Buy property in Alburquerque, Bohol. Hillside living, affordable land, 15 minutes from Tagbilaran. Browse listings at Island Properties PH.",
  },
  {
    slug: "carmen",
    name: "Carmen, Bohol",
    name_ko: "카르멘, 보홀",
    tagline: "Gateway to the Chocolate Hills",
    tagline_ko: "초콜릿 힐스의 관문",
    description: `Carmen is home to the Chocolate Hills — Bohol's most iconic landmark and a UNESCO World Heritage nominee. The town sits in the heart of Bohol's interior, surrounded by rolling hills and rich agricultural land. Tourism infrastructure is growing fast around the Chocolate Hills complex. For buyers with vision, Carmen represents one of Bohol's most distinctive long-term land investment opportunities.`,
    description_ko: `카르멘은 보홀의 가장 상징적인 명소이자 유네스코 세계유산 후보인 초콜릿 힐스의 본고장입니다. 보홀 내륙 중심부에 위치하며 구릉진 언덕과 비옥한 농경지에 둘러싸여 있습니다. 초콜릿 힐스 단지 주변의 관광 인프라가 빠르게 성장하고 있어, 장기적 안목의 구매자에게 보홀에서 가장 독특한 토지 투자 기회 중 하나입니다.`,
    keywords: ["carmen bohol property", "chocolate hills real estate", "buy land carmen bohol", "bohol interior property investment"],
    locationMatch: ["Carmen"],
    highlights: [
      "Home of the iconic Chocolate Hills",
      "UNESCO World Heritage nominee",
      "Growing tourism infrastructure",
      "Agricultural and eco-resort land available",
      "45 minutes from Tagbilaran",
    ],
    seoTitle: "Carmen Bohol Properties for Sale | Island Properties PH",
    seoDescription: "Buy property near the Chocolate Hills, Carmen Bohol. Growing tourism area, land investment potential. Browse listings at Island Properties PH.",
  },
];
